// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using WebApplication1ML.Model;
using System.Linq;

namespace WebApplication1ML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Title = @"The Story of the Kelly Gang",
                Description = @"True story of notorious Australian outlaw Ned Kelly (1855-80).",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            var scores = ConsumeModel.GetScores(predictionResult);

            Console.WriteLine("");
            Console.WriteLine("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
            foreach (ScoreOutput item in scores.Take(5))
            {
                Console.WriteLine(item.Label + " :: " + item.ScorePercent + "%");

            }
            Console.WriteLine("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
            Console.WriteLine("");

            Console.WriteLine("Using model to make single prediction -- Comparing actual Genre with predicted Genre from sample data...\n\n");
            Console.WriteLine($"Title: {sampleData.Title}");
            Console.WriteLine($"Description: {sampleData.Description}");
            Console.WriteLine($"\n\nPredicted Genre value {predictionResult.Prediction} \nPredicted Genre scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
